//# DS v2: organizmy
const { s, b } = await board('Organizmy', 5300);
const grow = n => { n.layoutGrow = 1; return n; }; const out = [];
const border = (n, side) => { n.strokes = paint('outline-variant'); n.strokeWeight = 1; n.strokeAlign = 'INSIDE'; n.strokeTopWeight = side === 'top' ? 1 : 0; n.strokeBottomWeight = side === 'bottom' ? 1 : 0; n.strokeLeftWeight = 0; n.strokeRightWeight = 0; };
if (!findComp('App header')) { const c = comp('App header', 'HORIZONTAL', { gap: 'md', fill: 'background', counterAxisAlignItems: 'CENTER' }); c.setBoundVariable('paddingTop', V('spacing/lg')); c.setBoundVariable('paddingBottom', V('spacing/md')); c.setBoundVariable('paddingLeft', V('spacing/xl')); c.setBoundVariable('paddingRight', V('spacing/xl')); fixedW(c, 402); border(c, 'bottom');
  const av = inst('Avatar', 'Size=44'); av.name = 'Avatar'; c.appendChild(av); const col = box('Child', 'VERTICAL', { gap: '2xs' }); c.appendChild(col); grow(col);
  const nr = box('Name', 'HORIZONTAL', { gap: '2xs', counterAxisAlignItems: 'CENTER' }); col.appendChild(nr); const name = await txt('Julia', 'headline/lg'); name.name = 'Name text'; nr.appendChild(name); nr.appendChild(iconInst('expand_more', 28, 'on-surface-variant'));
  const cls = await txt('klasa 1, SP Łady', 'body/2xs', 'on-surface-variant'); cls.name = 'Class'; col.appendChild(cls);
  const set = box('Button settings', 'HORIZONTAL', { primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER' }); set.primaryAxisSizingMode = 'FIXED'; set.counterAxisSizingMode = 'FIXED'; set.resize(44, 44); sizeVar(set, 'width', 'touch'); sizeVar(set, 'height', 'touch'); set.appendChild(iconInst('settings', 28, 'on-surface-variant')); c.appendChild(set);
  const k = { n: prop(c, 'Name', 'TEXT', 'Julia'), cl: prop(c, 'Class', 'TEXT', 'klasa 1, SP Łady') }; name.componentPropertyReferences = { characters: k.n }; cls.componentPropertyReferences = { characters: k.cl }; exposeAll(c);
  c.description = 'Stały nagłówek zakładek. Tap w awatar otwiera arkusz zdjęcia (ukryta funkcja, bez ikony aparatu), imię ze strzałką otwiera listę dzieci z przyciemnieniem tła, ikona otwiera Ustawienia. Bez daty, stempla danych i ikony odświeżania: odświeża przeciągnięcie listy w dół.'; await entry(b, 'App header', c.description, c); out.push('App header'); }
if (!findComp('Tab bar')) { const TABS = [['Teraz', 'home'], ['Zadania', 'task_alt'], ['Oceny', 'grading'], ['Wiadomości', 'mail'], ['Plan', 'calendar_month']]; const comps = [];
  for (const [active] of TABS) { const c = comp('Active=' + active, 'HORIZONTAL', { fill: 'surface-bar' }); c.setBoundVariable('paddingTop', V('spacing/s6')); c.setBoundVariable('paddingBottom', V('spacing/xs')); c.setBoundVariable('paddingLeft', V('spacing/xs')); c.setBoundVariable('paddingRight', V('spacing/xs')); fixedW(c, 402); border(c, 'top');
    for (const [label, ic] of TABS) { const t = inst('Tab item', label === active ? 'Active=True' : 'Active=False'); t.name = 'Tab ' + label; setProp(t, 'Label', label); setProp(t, 'Icon', findComp('Icon/' + ic).id); if (label === 'Teraz') setProp(t, 'Show badge', true); c.appendChild(t); grow(t); }
    comps.push(c); }
  const set = variants('Tab bar', comps, 'Dolna nawigacja: 5 zakładek, zawsze przyklejona do dołu ekranu, także przy krótkiej treści. Licznik na „Teraz" = liczba otwartych spraw. Ekrany przykrywające (Ustawienia, Frekwencja) i arkusze jej nie pokazują.'); set.layoutMode = 'VERTICAL'; set.itemSpacing = 16; for (const c of set.children) exposeAll(c);
  await entry(b, 'Tab bar', set.description, set); out.push('Tab bar'); }
if (!findComp('Sheet header')) { const c = comp('Sheet header', 'VERTICAL', { fill: 'surface' }); fixedW(c, 402); c.setBoundVariable('topLeftRadius', V('radius/2xl')); c.setBoundVariable('topRightRadius', V('radius/2xl')); const g = inst('Grabber'); c.appendChild(g); fillW(g); const kw = box('Kicker wrap', 'HORIZONTAL', { counterAxisAlignItems: 'CENTER' }); kw.setBoundVariable('paddingLeft', V('spacing/xl')); kw.setBoundVariable('paddingRight', V('spacing/xl')); kw.counterAxisSizingMode = 'FIXED'; kw.resize(402, 28); c.appendChild(kw); fillW(kw); const t = await txt('Wiadomość', 'label/sm', 'on-surface-variant'); t.name = 'Kicker'; kw.appendChild(t);
  const k = { sk: prop(c, 'Show kicker', 'BOOLEAN', true), t: prop(c, 'Kicker', 'TEXT', 'Wiadomość') }; kw.componentPropertyReferences = { visible: k.sk }; t.componentPropertyReferences = { characters: k.t };
  c.description = 'Góra arkusza dolnego: uchwyt + nadtytuł (rodzaj treści). Arkusz otwiera się na 64% wysokości nad Scrim, przewinięcie treści rozwija go na pełny ekran. Bez przycisku „Zamknij".'; await entry(b, 'Sheet header', c.description, c); out.push('Sheet header'); }
if (!findComp('Sheet actions')) { const comps = []; for (const kind of ['Primary + Secondary', 'Secondary', 'Primary']) { const c = comp('Actions=' + kind, 'HORIZONTAL', { gap: 'sm', fill: 'surface' }); c.setBoundVariable('paddingTop', V('spacing/md')); c.setBoundVariable('paddingBottom', V('spacing/lg')); c.setBoundVariable('paddingLeft', V('spacing/xl')); c.setBoundVariable('paddingRight', V('spacing/xl')); fixedW(c, 402); border(c, 'top');
    if (kind !== 'Secondary') { const p = inst('Button', 'Style=Primary, State=Default'); p.name = 'Primary'; c.appendChild(p); grow(p); } if (kind !== 'Primary') { const r = inst('Button', 'Style=Secondary, State=Default'); r.name = 'Secondary'; setProp(r, 'Label', kind === 'Secondary' ? 'Zamknij' : 'Odpowiedz'); c.appendChild(r); } comps.push(c); }
  const set = variants('Sheet actions', comps, 'Pasek akcji arkusza: jedna akcja główna + opcjonalna druga („Zrobione" / „Odpowiedz", „Wyślij" / „Anuluj", „Zapisz" / „Anuluj"). Przyciski 44 px.'); for (const c of set.children) exposeAll(c); await entry(b, 'Sheet actions', set.description, set); out.push('Sheet actions'); }
if (!findComp('Child menu')) { const c = comp('Child menu', 'VERTICAL', { fill: 'surface', radius: 'xl' }); fixedW(c, 370); c.clipsContent = true; await c.setEffectStyleIdAsync(ES('elevation/menu').id);
  for (const [i, [n, sub, cur]] of [['Julia', 'klasa 1, SP Łady', true], ['Drugie dziecko', 'klasa 4, SP Łady', false]].entries()) { const r = inst('List row', 'Leading=Avatar, Trailing=None'); r.name = 'Child ' + (i + 1); setProp(r, 'Title', n); setProp(r, 'Subtitle', sub); const a = r.findOne(x => x.name === 'Leading'); if (a) setProp(a, 'Initials', n[0]); c.appendChild(r); fillW(r); if (i) border(r, 'top'); if (cur) { const chk = iconInst('check', 24, 'primary'); c.appendChild(chk); chk.layoutPositioning = 'ABSOLUTE'; chk.x = 370 - 16 - 24; chk.y = 22; } }
  const note = box('Note', 'VERTICAL', { pad: ['md', 'lg'] }); border(note, 'top'); c.appendChild(note); fillW(note); note.appendChild(await txt('Lista dzieci pochodzi z konta rodzica w Librusie.', 'body/xs', 'on-surface-variant')); exposeAll(c);
  c.description = 'Lista dzieci rozwijana spod imienia w nagłówku. Pływa nad treścią (elevation/menu) na Scrim, jak arkusz dolny.'; await entry(b, 'Child menu', c.description, c); out.push('Child menu'); }
if (!findComp('Cover top bar')) { const c = comp('Cover top bar', 'HORIZONTAL', { primaryAxisAlignItems: 'SPACE_BETWEEN', counterAxisAlignItems: 'CENTER' }); c.setBoundVariable('paddingTop', V('spacing/xl')); c.setBoundVariable('paddingBottom', V('spacing/s10')); c.setBoundVariable('paddingLeft', V('spacing/xl')); c.setBoundVariable('paddingRight', V('spacing/lg')); fixedW(c, 402);
  const t = await txt('Ustawienia', 'headline/lg'); t.name = 'Title'; c.appendChild(t); const x = box('Button close', 'HORIZONTAL', { primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER', fill: 'neutral-container' }); x.primaryAxisSizingMode = 'FIXED'; x.counterAxisSizingMode = 'FIXED'; x.resize(44, 44); sizeVar(x, 'width', 'touch'); sizeVar(x, 'height', 'touch'); radius(x, 'full'); x.appendChild(iconInst('close', 24, 'on-surface')); c.appendChild(x);
  const k = prop(c, 'Title', 'TEXT', 'Ustawienia'); t.componentPropertyReferences = { characters: k }; c.description = 'Pasek ekranu przykrywającego (Ustawienia, Frekwencja): zakrywa nagłówek aplikacji i dolną nawigację, jedyna kontrolka wyjścia to „X".'; await entry(b, 'Cover top bar', c.description, c); out.push('Cover top bar'); }
fitSection(s, b);
await shot(b, { name: 'ds-org', scale: 0.45 });
const mb = section('Molekuły').children.find(n => n.name === 'Board'); await shot(mb, { name: 'ds-mol', scale: 0.3 });
return out;
