//# DS v2: strona startowa (zasady, konwencje, kontrasty)
const sec = section('Start') || (() => { const x = figma.createSection(); x.name = 'Start'; dsPage.appendChild(x); x.x = -2200; x.y = 0; return x; })();
let root = sec.children.find(n => n.name === 'Start board'); if (root) root.remove();
root = box('Start board', 'VERTICAL', { gap: '2xl', pad: ['3xl', '3xl'], fill: 'background' }); sec.appendChild(root); root.x = 80; root.y = 80; root.counterAxisSizingMode = 'FIXED'; root.resize(1500, 100); root.primaryAxisSizingMode = 'AUTO';
const h = async (t, style) => { const w = box('H', 'VERTICAL', {}); root.appendChild(w); fillW(w); const x = await txt(t, style); w.appendChild(x); fillW(x); x.textAutoResize = 'HEIGHT'; return x; };
const p = async (t) => { const x = await txt(t, 'body/md', 'on-surface-variant'); root.appendChild(x); fillW(x); x.textAutoResize = 'HEIGHT'; return x; };
await h('FLibrus Design System', 'headline/lg');
await p('Źródło prawdy dla makiet FLibrusa. Strona „Mockupy" składa się z instancji tych komponentów: zmiana tutaj zmienia wszystkie ekrany. Nazwy tokenów i komponentów są zgodne z formatem DESIGN.md (Stitch), więc plik da się wyeksportować dla agentów kodujących.');
await h('Jak korzystać', 'title/lg');
await p('1. Nie odczepiaj instancji. Jeśli czegoś brakuje, dodaj właściwość do komponentu albo nowy wariant.\n2. Nie wpisuj kolorów ani odstępów ręcznie: wszystko wiąż ze zmiennymi (Fill → zmienna, padding/gap → spacing/…).\n3. Tekst tylko ze stylów (headline/…, title/…, body/…, label/…, calendar/…).\n4. Ikony to komponenty Icon/… podmieniane przez właściwość Icon (INSTANCE_SWAP), nigdy nowy wariant na ikonę.\n5. Motyw ciemny to kolekcja „Color Dark" o tych samych nazwach tokenów (plan Starter daje 1 tryb na kolekcję).');
await h('Konwencje nazw', 'title/lg');
await p('Komponenty: Nazwa po angielsku (Button, List row, Bottom sheet). Warianty: Property=Value (Style=Primary, State=Default). Właściwości: Label, Show icon, Icon, Value, Show chips. Opisy komponentów po polsku, bo są instrukcją dla projektanta i dla agenta.\nZmienne: color/…, spacing/… (skala liczbowa 50–800), radius/…, size/…, font/…. Prymitywy (blue/600, neutral/900) są ukryte przed pickerem: komponenty wiążą się wyłącznie z tokenami semantycznymi.');
await h('Kontrast (WCAG AA)', 'title/lg');
const PAIRS = [['on-surface', 'surface', 'Tekst główny'], ['on-surface-variant', 'surface', 'Tekst pomocniczy'], ['on-surface-variant', 'background', 'Tekst pomocniczy na tle'], ['on-primary-container', 'primary-container', 'Karta podsumowania'], ['summary-secondary', 'primary-container', 'Szczegół na karcie'], ['primary', 'surface', 'Link, akcent'], ['warning', 'warning-container', 'Chip po terminie'], ['on-success-container', 'success-container', 'Chip na dziś'], ['success', 'surface', 'Wartość pozytywna'], ['error', 'background', 'Błąd walidacji'], ['on-badge', 'badge', 'Licznik'], ['on-inverse-surface', 'inverse-surface', 'Przycisk główny']];
const lum = c => { const f = v => v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); return 0.2126 * f(c.r) + 0.7152 * f(c.g) + 0.0722 * f(c.b); };
const byId = Object.fromEntries(_vars.map(v => [v.id, v])); const resolve = v => { let val = v.valuesByMode[Object.keys(v.valuesByMode)[0]]; while (val && val.type === 'VARIABLE_ALIAS') { v = byId[val.id]; val = v.valuesByMode[Object.keys(v.valuesByMode)[0]]; } return val; };
const rows = []; for (const [fg, bg, use] of PAIRS) for (const theme of ['Color', 'Color Dark']) { const a = lum(resolve(V('color/' + fg, theme))), b2 = lum(resolve(V('color/' + bg, theme))); const cr = (Math.max(a, b2) + 0.05) / (Math.min(a, b2) + 0.05); rows.push({ fg, bg, use, theme: theme === 'Color' ? 'jasny' : 'ciemny', cr: Math.round(cr * 100) / 100 }); }
const table = box('Contrast', 'VERTICAL', { fill: 'surface', radius: 'xl' }); table.clipsContent = true; root.appendChild(table); fillW(table);
for (const [i, r] of rows.entries()) { const line = box('Row', 'HORIZONTAL', { gap: 'lg', pad: ['sm', 'lg'], counterAxisAlignItems: 'CENTER' }); if (i) { line.strokes = paint('outline-variant'); line.strokeWeight = 1; line.strokeAlign = 'INSIDE'; line.strokeTopWeight = 1; line.strokeBottomWeight = line.strokeLeftWeight = line.strokeRightWeight = 0; } table.appendChild(line); fillW(line);
  const sw = box('Sample', 'HORIZONTAL', { pad: ['xs', 'sm'], radius: 'sm' }); sw.fills = paint('color/' + r.bg === 'color/' ? r.bg : r.bg, r.theme === 'jasny' ? 'Color' : 'Color Dark'); const st = await txt('Aa', 'label/md', r.fg, r.theme === 'jasny' ? 'Color' : 'Color Dark'); sw.appendChild(st); line.appendChild(sw); sw.resize(56, sw.height);
  const l1 = await txt(r.fg + ' na ' + r.bg, 'body/sm'); line.appendChild(l1); l1.resize(420, l1.height); const l2 = await txt(r.theme, 'body/sm', 'on-surface-variant'); line.appendChild(l2); l2.resize(90, l2.height);
  const l3 = await txt(r.cr.toFixed(2) + ':1  ' + (r.cr >= 4.5 ? 'AA' : r.cr >= 3 ? 'AA large / UI' : 'PONIŻEJ AA'), 'label/md', r.cr >= 4.5 ? 'success' : r.cr >= 3 ? 'warning' : 'error'); line.appendChild(l3); l3.resize(260, l3.height);
  const l4 = await txt(r.use, 'body/sm', 'on-surface-variant'); line.appendChild(l4); l4.layoutGrow = 1; }
sec.resizeWithoutConstraints(root.width + 160, root.height + 160);
await shot(root, { name: 'ds-start', scale: 0.42 });
return { rows: rows.length, fails: rows.filter(r => r.cr < 3).map(r => r.fg + '/' + r.bg + ' ' + r.theme + ' ' + r.cr), belowAA: rows.filter(r => r.cr < 4.5 && r.cr >= 3).map(r => r.fg + '/' + r.bg + ' ' + r.theme + ' ' + r.cr) };
