//# DS v2: molekuły, część 2
const { s, b } = await board('Molekuły', 3300);
const grow = n => { n.layoutGrow = 1; return n; }; const out = [];
const has = n => !!findComp(n);
if (!has('Segmented control')) { const comps = []; const LABELS = { 2: ['Odebrane', 'Wysłane'], 3: ['Systemowy', 'Jasny', 'Ciemny'], 4: ['Dzień', 'Tydzień', 'Miesiąc', 'Rok'] };
  for (const n of [2, 3, 4]) for (let a = 1; a <= n; a++) { const c = comp('Segments=' + n + ', Active=' + a, 'HORIZONTAL', { gap: '2xs', fill: 'neutral-container', radius: 'md' }); for (const p of ['paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight']) c.setBoundVariable(p, V('spacing/2xs')); fixedW(c, 370);
    for (let i = 1; i <= n; i++) { const seg = box('Segment ' + i, 'HORIZONTAL', { gap: 's6', primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER' }); seg.counterAxisSizingMode = 'FIXED'; seg.resize(80, 44); sizeVar(seg, 'height', 'touch'); radius(seg, 'sm'); if (i === a) seg.fills = paint('surface'); c.appendChild(seg); grow(seg);
      const t = await txt(LABELS[n][i - 1], i === a ? 'label/md-strong' : 'label/md', i === a ? 'on-surface' : 'on-surface-variant'); t.name = 'Label ' + i; seg.appendChild(t); if (i === 1) { const bd = inst('Badge'); bd.name = 'Badge'; setProp(bd, 'Count', '2'); seg.appendChild(bd); } }
    comps.push(c); }
  const set = variants('Segmented control', comps, 'Przełącznik widoków (iOS): foldery poczty, widoki kalendarza, motyw, Miesiąc/Rok we frekwencji. Aktywny segment: surface + label/md-strong. Licznik nieprzeczytanych to Badge przy pierwszej etykiecie.'); set.resize(1240, set.height);
  const k = { l1: prop(set, 'Label 1', 'TEXT', 'Odebrane'), l2: prop(set, 'Label 2', 'TEXT', 'Wysłane'), l3: prop(set, 'Label 3', 'TEXT', 'Miesiąc'), l4: prop(set, 'Label 4', 'TEXT', 'Rok'), sb: prop(set, 'Show badge', 'BOOLEAN', false) };
  for (const c of set.children) { for (let i = 1; i <= 4; i++) { const t = c.findOne(x => x.name === 'Label ' + i); if (t) t.componentPropertyReferences = { characters: k['l' + i] }; } c.findOne(x => x.name === 'Badge').componentPropertyReferences = { visible: k.sb }; exposeAll(c); }
  await entry(b, 'Segmented control', set.description, set); out.push('Segmented control'); }
if (!has('Tab item')) { const comps = [];
  for (const on of [true, false]) { const c = comp('Active=' + (on ? 'True' : 'False'), 'VERTICAL', { gap: '2xs', counterAxisAlignItems: 'CENTER' }); c.counterAxisSizingMode = 'FIXED'; c.resize(72, 52); c.primaryAxisSizingMode = 'AUTO';
    const pill = box('Pill', 'HORIZONTAL', { primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER' }); pill.primaryAxisSizingMode = 'FIXED'; pill.counterAxisSizingMode = 'FIXED'; pill.resize(56, 30); sizeVar(pill, 'width', 'tab-pill-width'); sizeVar(pill, 'height', 'tab-pill-height'); radius(pill, 'full'); if (on) pill.fills = paint('primary-container'); pill.clipsContent = false;
    const ic = iconInst('home', 24, on ? 'on-primary-container' : 'on-surface-variant'); ic.name = 'Icon'; pill.appendChild(ic); const bd = inst('Badge'); bd.name = 'Badge'; pill.appendChild(bd); bd.layoutPositioning = 'ABSOLUTE'; bd.x = 32; bd.y = -3; c.appendChild(pill);
    const t = await txt('Teraz', 'label/xs', on ? 'on-surface' : 'on-surface-variant'); t.name = 'Label'; c.appendChild(t); comps.push(c); }
  const set = variants('Tab item', comps, 'Pozycja dolnej nawigacji: ikona 24 + etykieta. Aktywna ma tonalną pigułkę (Material 3). Licznik tylko na „Teraz" i tylko dla otwartych spraw.');
  const k = { l: prop(set, 'Label', 'TEXT', 'Teraz'), i: prop(set, 'Icon', 'INSTANCE_SWAP', findComp('Icon/home').id), sb: prop(set, 'Show badge', 'BOOLEAN', false) };
  for (const c of set.children) { c.findOne(n => n.name === 'Label').componentPropertyReferences = { characters: k.l }; c.findOne(n => n.name === 'Icon').componentPropertyReferences = { mainComponent: k.i }; c.findOne(n => n.name === 'Badge').componentPropertyReferences = { visible: k.sb }; exposeAll(c); }
  await entry(b, 'Tab item', set.description, set); out.push('Tab item'); }
progress(0.3, 'Pola');
if (!has('Text field')) { const comps = [];
  for (const type of ['Single', 'Multiline']) for (const [state, stroke, w] of [['Empty', 'outline', 1.5], ['Filled', 'outline', 1.5], ['Focus', 'focus', 2], ['Error', 'error', 1.5]]) { const c = comp('Type=' + type + ', State=' + state, 'VERTICAL', { gap: 's6' }); fixedW(c, 338);
    const l = await txt('Temat', 'label/md'); l.name = 'Label'; c.appendChild(l); const lw = l;
    const inp = box('Input', 'HORIZONTAL', { fill: 'background', radius: 'lg' }); inp.counterAxisAlignItems = type === 'Single' ? 'CENTER' : 'MIN'; inp.setBoundVariable('paddingLeft', V('spacing/lg')); inp.setBoundVariable('paddingRight', V('spacing/lg')); if (type === 'Multiline') { inp.setBoundVariable('paddingTop', V('spacing/md')); inp.setBoundVariable('paddingBottom', V('spacing/md')); }
    inp.counterAxisSizingMode = 'FIXED'; inp.resize(338, type === 'Single' ? 48 : 148); if (type === 'Single') sizeVar(inp, 'height', 'field'); inp.strokes = paint(stroke); inp.strokeWeight = w; inp.strokeAlign = 'INSIDE'; c.appendChild(inp); fillW(inp);
    const v = await txt(state === 'Filled' ? 'Koniki' : 'np. koniki, angielski', 'body/md', state === 'Filled' ? 'on-surface' : 'on-surface-variant'); v.name = 'Value'; inp.appendChild(v); grow(v); v.textAutoResize = 'HEIGHT';
    const e = await txt('Wpisz temat.', 'label/sm', 'error'); e.name = 'Error'; c.appendChild(e); if (state !== 'Error') e.visible = false; comps.push(c); }
  const set = variants('Text field', comps, 'Pole formularza: 48 px (Single) albo wielowierszowe. Etykieta zawsze widoczna nad polem. Stany: Empty (placeholder), Filled, Focus (obrys focus 2 px), Error (opis tekstem pod polem, fokus wraca na pierwsze błędne pole).'); set.resize(1500, set.height);
  const k = { sl: prop(set, 'Show label', 'BOOLEAN', true), l: prop(set, 'Label', 'TEXT', 'Temat'), v: prop(set, 'Value', 'TEXT', 'np. koniki, angielski'), e: prop(set, 'Error text', 'TEXT', 'Wpisz temat.') };
  for (const c of set.children) { c.findOne(n => n.name === 'Label').componentPropertyReferences = { visible: k.sl, characters: k.l }; c.findOne(n => n.name === 'Value').componentPropertyReferences = { characters: k.v }; c.findOne(n => n.name === 'Error').componentPropertyReferences = { characters: k.e }; }
  await entry(b, 'Text field', set.description, set); out.push('Text field'); }
if (!has('Static field')) { const c = comp('Static field', 'HORIZONTAL', { gap: 's10' }); c.setBoundVariable('paddingTop', V('spacing/md')); c.setBoundVariable('paddingBottom', V('spacing/md')); fixedW(c, 362); c.counterAxisAlignItems = 'MIN'; c.strokes = paint('outline-variant'); c.strokeWeight = 1; c.strokeAlign = 'INSIDE'; c.strokeTopWeight = 0; c.strokeLeftWeight = 0; c.strokeRightWeight = 0; c.strokeBottomWeight = 1;
  const l = await txt('Do', 'body/sm', 'on-surface-variant'); l.name = 'Label'; c.appendChild(l); l.resize(56, l.height); l.textAutoResize = 'HEIGHT'; const col = box('Value', 'VERTICAL', { gap: 's6' }); c.appendChild(col); grow(col); const v = await txt('Joanna Osęka-Więcławicz', 'title/sm'); v.name = 'Value text'; col.appendChild(v); fillW(v); v.textAutoResize = 'HEIGHT'; const ch = inst('Chip', 'Tone=Neutral'); ch.name = 'Chip'; setProp(ch, 'Label', 'Wychowawczyni'); setProp(ch, 'Show icon', false); col.appendChild(ch);
  const k = { l: prop(c, 'Label', 'TEXT', 'Do'), v: prop(c, 'Value', 'TEXT', 'Joanna Osęka-Więcławicz'), sc: prop(c, 'Show chip', 'BOOLEAN', true) }; l.componentPropertyReferences = { characters: k.l }; v.componentPropertyReferences = { characters: k.v }; ch.componentPropertyReferences = { visible: k.sc }; exposeAll(c);
  c.description = 'Pole tylko do odczytu w oknie odpowiedzi (Do, Temat). Rola odbiorcy jako chip pod nazwiskiem.'; await entry(b, 'Static field', c.description, c); out.push('Static field'); }
progress(0.5, 'Komunikaty');
if (!has('Banner')) { const c = comp('Banner', 'HORIZONTAL', { pad: ['md', 'lg'], fill: 'success-container', radius: 'lg' }); fixedW(c, 370); const t = await txt('Nie udało się odświeżyć. Pokazujemy ostatnie poprawne dane z 18.09.2026.', 'label/lg', 'on-success-container'); t.name = 'Text'; c.appendChild(t); grow(t); t.textAutoResize = 'HEIGHT'; const k = prop(c, 'Text', 'TEXT', t.characters); t.componentPropertyReferences = { characters: k };
  c.description = 'Komunikat stanu nad treścią (odświeżanie, błąd z ostatnimi poprawnymi danymi, potwierdzenie). Mówi, co się stało i co dalej. Nigdy nie wspomina o prototypie ani symulacji.'; await entry(b, 'Banner', c.description, c); out.push('Banner'); }
if (!has('Date nav')) { const c = comp('Date nav', 'HORIZONTAL', { gap: '2xs', counterAxisAlignItems: 'CENTER' }); const btn = name => { const x = box('Button ' + name, 'HORIZONTAL', { primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER' }); x.primaryAxisSizingMode = 'FIXED'; x.counterAxisSizingMode = 'FIXED'; x.resize(44, 44); sizeVar(x, 'width', 'touch'); sizeVar(x, 'height', 'touch'); x.appendChild(iconInst(name, 24, 'on-surface')); return x; };
  c.appendChild(btn('chevron_left')); const tw = box('Title wrap', 'HORIZONTAL', {}); tw.setBoundVariable('paddingLeft', V('spacing/xs')); tw.setBoundVariable('paddingRight', V('spacing/xs')); const t = await txt('Wrzesień 2026', 'headline/sm'); t.name = 'Title'; tw.appendChild(t); c.appendChild(tw); c.appendChild(btn('chevron_right')); const k = prop(c, 'Period', 'TEXT', 'Wrzesień 2026'); t.componentPropertyReferences = { characters: k };
  c.description = 'Nawigacja po okresie: strzałki po lewej i prawej stronie daty. Plan (dzień, tydzień, miesiąc, rok) i Frekwencja (nad kartą KPI, która zmienia się z okresem).'; await entry(b, 'Date nav', c.description, c); out.push('Date nav'); }
if (!has('Empty state')) { const c = comp('Empty state', 'VERTICAL', { counterAxisAlignItems: 'CENTER' }); c.setBoundVariable('paddingTop', V('spacing/3xl')); c.setBoundVariable('paddingLeft', V('spacing/lg')); c.setBoundVariable('paddingRight', V('spacing/lg')); c.setBoundVariable('paddingBottom', V('spacing/lg')); fixedW(c, 370);
  const circ = box('Icon circle', 'HORIZONTAL', { primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER', fill: 'neutral-container' }); circ.primaryAxisSizingMode = 'FIXED'; circ.counterAxisSizingMode = 'FIXED'; circ.resize(72, 72); sizeVar(circ, 'width', 'avatar-lg'); sizeVar(circ, 'height', 'avatar-lg'); radius(circ, 'full'); const ic = iconInst('task_alt', 36, 'on-surface-variant'); ic.name = 'Icon'; circ.appendChild(ic); c.appendChild(circ);
  const tw = box('Title wrap', 'VERTICAL', {}); tw.setBoundVariable('paddingTop', V('spacing/lg')); c.appendChild(tw); fillW(tw); const t = await txt('Brak zadań', 'headline/xs'); t.name = 'Title'; t.textAlignHorizontal = 'CENTER'; tw.appendChild(t); fillW(t); t.textAutoResize = 'HEIGHT';
  const bw = box('Body wrap', 'VERTICAL', {}); bw.setBoundVariable('paddingTop', V('spacing/sm')); c.appendChild(bw); const body = await txt('Gdy nauczyciel wpisze zadanie w Librusie, pojawi się tutaj z terminem.', 'body/md', 'on-surface-variant'); body.name = 'Body'; body.textAlignHorizontal = 'CENTER'; bw.appendChild(body); body.resize(304, body.height); body.textAutoResize = 'HEIGHT';
  const k = { i: prop(c, 'Icon', 'INSTANCE_SWAP', findComp('Icon/task_alt').id), t: prop(c, 'Title', 'TEXT', 'Brak zadań'), b: prop(c, 'Body', 'TEXT', body.characters) }; ic.componentPropertyReferences = { mainComponent: k.i }; t.componentPropertyReferences = { characters: k.t }; body.componentPropertyReferences = { characters: k.b };
  c.description = 'Pusty stan: mówi, dlaczego jest pusto i co sprawi, że coś się pojawi. Bez ilustracji, bez „No data".'; await entry(b, 'Empty state', c.description, c); out.push('Empty state'); }
progress(0.7, 'Wiadomości, KPI, kalendarz');
if (!has('Message card')) { const comps = []; for (const own of [false, true]) { const c = comp('Own=' + (own ? 'True' : 'False'), 'VERTICAL', { gap: 'md', pad: ['lg', 'lg'], fill: own ? 'primary-container' : 'surface', radius: 'xl' }); fixedW(c, 370);
    const head = box('Head', 'HORIZONTAL', { gap: 'md', counterAxisAlignItems: 'CENTER' }); c.appendChild(head); fillW(head); const a = inst('Avatar', 'Size=40'); a.name = 'Avatar'; setProp(a, 'Initials', own ? 'Ty' : 'JO'); head.appendChild(a); const col = box('Who', 'VERTICAL', { gap: '2xs' }); head.appendChild(col); grow(col);
    const n = await txt(own ? 'Twoja odpowiedź' : 'Joanna Osęka-Więcławicz', 'title/sm', own ? 'on-primary-container' : 'on-surface'); n.name = 'Name'; col.appendChild(n); fillW(n); n.textAutoResize = 'HEIGHT'; const m = await txt(own ? 'dziś, 18:16' : 'wychowawczyni, dziś, 15:13', 'body/xs', own ? 'on-primary-container' : 'on-surface-variant'); m.name = 'Meta'; col.appendChild(m);
    const body = await txt('Dzień dobry, od dwóch dni Julia nie ma małych zielonych ćwiczeń. Proszę dopilnować, aby trafiły do plecaka.', 'body/md', own ? 'on-primary-container' : 'on-surface'); body.name = 'Body'; c.appendChild(body); fillW(body); body.textAutoResize = 'HEIGHT'; comps.push(c); }
  const set = variants('Message card', comps, 'Treść wiadomości w wątku. Own=True: odpowiedź rodzica (tonalna). Pod kartą pole odpowiedzi i „Poprzednie wiadomości od tej osoby".');
  const k = { n: prop(set, 'Name', 'TEXT', 'Joanna Osęka-Więcławicz'), m: prop(set, 'Meta', 'TEXT', 'wychowawczyni, dziś, 15:13'), b: prop(set, 'Body', 'TEXT', 'Dzień dobry, od dwóch dni Julia nie ma małych zielonych ćwiczeń. Proszę dopilnować, aby trafiły do plecaka.') }; for (const c of set.children) { c.findOne(x => x.name === 'Name').componentPropertyReferences = { characters: k.n }; c.findOne(x => x.name === 'Meta').componentPropertyReferences = { characters: k.m }; c.findOne(x => x.name === 'Body').componentPropertyReferences = { characters: k.b }; exposeAll(c); }
  await entry(b, 'Message card', set.description, set); out.push('Message card'); }
if (!has('Quote')) { const c = comp('Quote', 'VERTICAL', { gap: 's6', pad: ['lg', 'lg'], fill: 'background', radius: 'lg' }); fixedW(c, 362); const by = await txt('Joanna Osęka-Więcławicz, dziś, 15:13:', 'label/sm', 'on-surface-variant'); by.name = 'By'; c.appendChild(by); const t = await txt('Dzień dobry, od dwóch dni Julia nie ma małych zielonych ćwiczeń. Proszę dopilnować, aby trafiły do plecaka.', 'body/sm', 'on-surface-variant'); t.name = 'Text'; c.appendChild(t); fillW(t); t.textAutoResize = 'HEIGHT';
  const k = { b: prop(c, 'By', 'TEXT', by.characters), t: prop(c, 'Text', 'TEXT', t.characters) }; by.componentPropertyReferences = { characters: k.b }; t.componentPropertyReferences = { characters: k.t }; c.description = 'Cytat poprzedniej wiadomości w oknie odpowiedzi.'; await entry(b, 'Quote', c.description, c); out.push('Quote'); }
if (!has('KPI card')) { const c = comp('KPI card', 'VERTICAL', { gap: '2xs', pad: ['lg', 'xl'], fill: 'surface', radius: 'xl' }); fixedW(c, 370); const v = await txt('100%', 'headline/lg', 'success'); v.name = 'Value'; c.appendChild(v); const t = await txt('Obecność na 55 z 55 lekcji', 'title/md'); t.name = 'Title'; c.appendChild(t); const d = await txt('0 nieobecności, 0 spóźnień we wrześniu', 'body/sm', 'on-surface-variant'); d.name = 'Detail'; c.appendChild(d);
  const k = { v: prop(c, 'Value', 'TEXT', '100%'), t: prop(c, 'Title', 'TEXT', t.characters), d: prop(c, 'Detail', 'TEXT', d.characters) }; v.componentPropertyReferences = { characters: k.v }; t.componentPropertyReferences = { characters: k.t }; d.componentPropertyReferences = { characters: k.d }; c.description = 'Karta wskaźnika dla wybranego okresu (Frekwencja). Wartość zmienia się razem z Date nav nad kartą.'; await entry(b, 'KPI card', c.description, c); out.push('KPI card'); }
if (!has('Calendar event')) { const comps = []; for (const [kind, bg, fg] of [['Lesson', 'primary-container', 'on-primary-container'], ['Own', 'success-container', 'on-success-container'], ['Task', 'warning-container', 'warning'], ['School', 'neutral-container', 'on-surface']]) { const c = comp('Kind=' + kind, 'VERTICAL', { fill: bg, radius: 'sm' }); c.setBoundVariable('paddingTop', V('spacing/xs')); c.setBoundVariable('paddingBottom', V('spacing/xs')); c.setBoundVariable('paddingLeft', V('spacing/sm')); c.setBoundVariable('paddingRight', V('spacing/sm')); c.counterAxisSizingMode = 'FIXED'; c.primaryAxisSizingMode = 'FIXED'; c.resize(316, 45); c.clipsContent = true;
    const t = await txt(kind === 'Own' ? 'Koniki' : kind === 'Task' ? 'Kaligrafia: wzory do strony 5' : kind === 'School' ? 'Sprzątanie Świata' : 'Edukacja wczesnoszkolna', 'label/md', fg); t.name = 'Title'; c.appendChild(t); fillW(t); t.textTruncation = 'ENDING'; t.maxLines = 1; const m = await txt(kind === 'Own' ? '16:00 do 17:00, własne zajęcia' : '7:45 do 8:30, Lekcja 1', 'calendar/event-meta', fg); m.name = 'Meta'; c.appendChild(m); fillW(m); comps.push(c); }
  const set = variants('Calendar event', comps, 'Blok w siatce godzin. Lesson: lekcja z planu, Own: własne zajęcia rodzica, Task: zadanie w pasku „cały dzień", School: wydarzenie szkolne. Wysokość instancji = czas trwania (60 px na godzinę w dniu, 52 px w tygodniu).');
  const k = { t: prop(set, 'Title', 'TEXT', 'Edukacja wczesnoszkolna'), sm: prop(set, 'Show meta', 'BOOLEAN', true), m: prop(set, 'Meta', 'TEXT', '7:45 do 8:30, Lekcja 1') }; for (const c of set.children) { c.findOne(x => x.name === 'Title').componentPropertyReferences = { characters: k.t }; c.findOne(x => x.name === 'Meta').componentPropertyReferences = { visible: k.sm, characters: k.m }; }
  await entry(b, 'Calendar event', set.description, set); out.push('Calendar event'); }
if (!has('Refresh indicator')) { const c = comp('Refresh indicator', 'HORIZONTAL', { gap: 'sm', primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER' }); c.primaryAxisSizingMode = 'FIXED'; c.counterAxisSizingMode = 'FIXED'; c.resize(370, 48); c.appendChild(inst('Spinner')); const t = await txt('Odświeżam dane', 'label/sm', 'on-surface-variant'); t.name = 'Text'; c.appendChild(t); c.description = 'Wiersz nad treścią po przeciągnięciu listy w dół (zastępuje ikonę odświeżania w nagłówku).'; await entry(b, 'Refresh indicator', c.description, c); out.push('Refresh indicator'); }
if (!has('Disclosure')) { const comps = []; for (const open of [false, true]) { const c = comp('Expanded=' + (open ? 'True' : 'False'), 'HORIZONTAL', { gap: 'sm', counterAxisAlignItems: 'CENTER' }); c.counterAxisSizingMode = 'FIXED'; c.resize(370, 44); sizeVar(c, 'height', 'touch'); fixedW(c, 370); c.setBoundVariable('paddingLeft', V('spacing/xs')); const ic = iconInst(open ? 'expand_more' : 'chevron_right', 20, 'on-surface'); c.appendChild(ic); const t = await txt('Pokaż pozostałe ogłoszenia (12)', 'title/sm'); t.name = 'Label'; c.appendChild(t); comps.push(c); }
  const set = variants('Disclosure', comps, 'Rozwijana grupa: „Pokaż pozostałe ogłoszenia (12)", „Zrobione (2)", „Archiwum (1)", „Oferta zajęć dodatkowych".'); const k = prop(set, 'Label', 'TEXT', 'Pokaż pozostałe ogłoszenia (12)'); for (const c of set.children) c.findOne(x => x.name === 'Label').componentPropertyReferences = { characters: k }; await entry(b, 'Disclosure', set.description, set); out.push('Disclosure'); }
if (!has('Completed row')) { const c = comp('Completed row', 'HORIZONTAL', { gap: 'sm', fill: 'surface', counterAxisAlignItems: 'CENTER' }); c.setBoundVariable('paddingTop', V('spacing/s10')); c.setBoundVariable('paddingBottom', V('spacing/s10')); c.setBoundVariable('paddingLeft', V('spacing/lg')); c.setBoundVariable('paddingRight', V('spacing/md')); fixedW(c, 370); const t = await txt('Ćwiczenia polonistyczne str. 17-19 + matematyczne do str. 10', 'body/md', 'on-surface-variant'); t.name = 'Title'; t.textDecoration = 'STRIKETHROUGH'; c.appendChild(t); grow(t); t.textAutoResize = 'HEIGHT'; const u = inst('Button', 'Style=Secondary, State=Default'); u.name = 'Undo'; setProp(u, 'Label', 'Cofnij'); c.appendChild(u); const k = prop(c, 'Title', 'TEXT', t.characters); t.componentPropertyReferences = { characters: k }; exposeAll(c);
  c.description = 'Pozycja zrobiona lub zarchiwizowana: przekreślony tytuł i „Cofnij".'; await entry(b, 'Completed row', c.description, c); out.push('Completed row'); }
fitSection(s, b);
return out;
