//# DS v2: atomy (stany, API po angielsku, nowe atomy)
const { s, b } = await board('Atomy', 2000);
const out = [];
// Button v2
removeDoc('Button');
{ const STYLES = { Primary: ['inverse-surface', 'on-inverse-surface'], Secondary: ['neutral-container', 'on-surface'], Outline: [null, 'on-surface'], Text: [null, 'primary'] }; const comps = [];
  for (const [style, [bg, fg]] of Object.entries(STYLES)) for (const state of ['Default', 'Pressed', 'Disabled']) {
    const c = figma.createComponent(); c.name = 'Style=' + style + ', State=' + state; c.layoutMode = 'HORIZONTAL'; c.primaryAxisAlignItems = 'CENTER'; c.counterAxisAlignItems = 'CENTER'; c.counterAxisSizingMode = 'FIXED'; c.resize(120, 44); c.primaryAxisSizingMode = 'AUTO';
    sizeVar(c, 'height', 'touch'); c.setBoundVariable('itemSpacing', V('spacing/xs')); for (const p of ['paddingLeft', 'paddingRight']) c.setBoundVariable(p, V('spacing/xl')); radius(c, style === 'Outline' ? 'full' : 'md');
    const dis = state === 'Disabled'; c.fills = dis && bg ? paint('disabled-container') : bg ? paint(bg) : [];
    if (style === 'Outline') { c.strokes = paint(dis ? 'outline-variant' : 'outline'); c.strokeWeight = 1.5; c.strokeAlign = 'INSIDE'; }
    const color = dis ? 'on-disabled' : fg; const ic = iconInst('reply', 20, color); ic.name = 'Icon'; c.appendChild(ic); const t = await txt('Zrobione', 'label/lg', color); t.name = 'Label'; c.appendChild(t);
    if (state === 'Pressed') { const o = figma.createFrame(); o.name = 'State layer'; o.resize(120, 44); o.fills = paint(style === 'Primary' ? 'on-inverse-surface' : 'state-pressed'); if (style === 'Primary') o.opacity = 0.16; c.appendChild(o); o.layoutPositioning = 'ABSOLUTE'; o.x = 0; o.y = 0; o.constraints = { horizontal: 'STRETCH', vertical: 'STRETCH' }; }
    comps.push(c); }
  const set = variants('Button', comps, 'Przycisk 44 px. Primary: jedna główna akcja w karcie lub arkuszu (czarny, w ciemnym motywie biały). Secondary: akcje poboczne („Szczegóły", „Anuluj", „Archiwizuj"). Outline: akcja kontekstowa w pasku („Dziś"). Text: akcja w tekście („Odśwież teraz"). Stany: Default, Pressed (nakładka state-pressed), Disabled. Etykieta to czasownik, bez słów „symuluj" czy „prototyp".');
  set.resize(760, set.height); const k = { l: prop(set, 'Label', 'TEXT', 'Zrobione'), si: prop(set, 'Show icon', 'BOOLEAN', false), i: prop(set, 'Icon', 'INSTANCE_SWAP', findComp('Icon/reply').id) };
  for (const c of set.children) { c.findOne(n => n.name === 'Label').componentPropertyReferences = { characters: k.l }; c.findOne(n => n.name === 'Icon').componentPropertyReferences = { visible: k.si, mainComponent: k.i }; }
  await entry(b, 'Button', set.description, set); out.push('Button ' + set.children.length); }
// Chip: bez ikony końcowej, API po angielsku
{ const set = findComp('Chip'); for (const c of set.children) { const tr = c.findOne(n => n.name === 'Trailing icon'); if (tr) tr.remove(); c.counterAxisSizingMode = 'FIXED'; sizeVar(c, 'height', 'chip'); }
  for (const [key, def] of Object.entries(set.componentPropertyDefinitions)) { const base = key.split('#')[0]; if (base === 'Ikona końcowa') set.deleteComponentProperty(key); else if (base === 'Ikona') set.editComponentProperty(key, { name: 'Show icon' }); else if (base === 'Ikona ↔') set.editComponentProperty(key, { name: 'Icon' }); }
  set.description = 'Tag metadanych (data, źródło, rola, stan). Reguła terminu zadania: po terminie = Warning, termin dziś = Success, termin w przyszłości = Neutral. Info = „Nowe" (nieprzeczytane) i legenda lekcji. Rola nadawcy („Wychowawczyni") to zawsze chip, nie dopisek w tekście.'; out.push('Chip'); }
for (const [name, from, to] of [['Avatar', 'Inicjał', 'Initials'], ['Badge', 'Liczba', 'Count'], ['Icon tile', 'Ikona ↔', 'Icon']]) { const c = findComp(name); for (const key of Object.keys(c.componentPropertyDefinitions)) if (key.split('#')[0] === from) c.editComponentProperty(key, { name: to }); }
for (const v of findComp('Avatar').children) sizeVar(v, 'width', 'avatar-' + ({ 40: 'sm', 44: 'md', 72: 'lg' }[Math.round(v.width)])), sizeVar(v, 'height', 'avatar-' + ({ 40: 'sm', 44: 'md', 72: 'lg' }[Math.round(v.height)]));
for (const v of findComp('Icon tile').children) { radius(v, 'sm'); sizeVar(v, 'width', 'tile'); sizeVar(v, 'height', 'tile'); if (v.name.includes('Success')) v.findOne(n => n.name === 'Icon').children[0].fills = paint('on-success'); }
for (const v of findComp('Checkbox').children) { sizeVar(v, 'width', 'checkbox'); sizeVar(v, 'height', 'checkbox'); }
for (const v of findComp('Switch').children) { sizeVar(v, 'width', 'switch-width'); sizeVar(v, 'height', 'switch-height'); v.paddingLeft = v.paddingRight = 2; v.setBoundVariable('paddingLeft', V('spacing/2xs')); v.setBoundVariable('paddingRight', V('spacing/2xs')); }
removeDoc('Unread dot');
progress(0.6, 'Nowe atomy');
if (!findComp('FAB')) { const c = comp('FAB', 'HORIZONTAL', { gap: 'sm', fill: 'inverse-surface', radius: 'xl', counterAxisAlignItems: 'CENTER' }); c.counterAxisSizingMode = 'FIXED'; c.resize(140, 52); c.primaryAxisSizingMode = 'AUTO'; c.setBoundVariable('paddingLeft', V('spacing/lg')); c.setBoundVariable('paddingRight', V('spacing/xl')); await c.setEffectStyleIdAsync(ES('elevation/fab').id);
  const ic = iconInst('edit', 24, 'on-inverse-surface'); ic.name = 'Icon'; c.appendChild(ic); const t = await txt('Napisz', 'title/sm', 'on-inverse-surface'); t.name = 'Label'; c.appendChild(t);
  const k1 = prop(c, 'Label', 'TEXT', 'Napisz'), k2 = prop(c, 'Icon', 'INSTANCE_SWAP', findComp('Icon/edit').id); t.componentPropertyReferences = { characters: k1 }; ic.componentPropertyReferences = { mainComponent: k2 };
  c.description = 'Przycisk pływający nad listą (jedyny element z cieniem elevation/fab): „Napisz" w Wiadomościach, „Dodaj zajęcia" w Planie. 16 px od prawej krawędzi, 13 px nad dolną nawigacją.'; await entry(b, 'FAB', c.description, c); out.push('FAB'); }
if (!findComp('Progress bar')) { const comps = []; for (const v of [0, 25, 50, 75, 100]) { const c = figma.createComponent(); c.name = 'Value=' + v; c.resize(338, 6); radius(c, 'full'); c.fills = paint('summary-track'); c.clipsContent = true; const bar = figma.createFrame(); bar.name = 'Bar'; bar.resize(Math.max(338 * v / 100, 0.01), 6); radius(bar, 'full'); bar.fills = paint('primary'); c.appendChild(bar); bar.constraints = { horizontal: 'SCALE', vertical: 'STRETCH' }; if (!v) bar.visible = false; comps.push(c); }
  const set = variants('Progress bar', comps, 'Pasek prawdziwego postępu (zamknięte sprawy z otwartych). Tor: summary-track, wypełnienie: primary. Wartość zaokrąglana do najbliższego wariantu.'); set.layoutMode = 'VERTICAL'; set.itemSpacing = 16; await entry(b, 'Progress bar', set.description, set); out.push('Progress bar'); }
if (!findComp('Scrim')) { const c = figma.createComponent(); c.name = 'Scrim'; c.resize(402, 874); c.fills = paint('scrim'); c.description = 'Przyciemnienie tła (42%) pod arkuszem dolnym i listą dzieci. Tap zamyka warstwę.'; const holder = box('Scrim preview', 'VERTICAL', {}); holder.appendChild(c); c.resize(402, 120); await entry(b, 'Scrim', c.description, holder); out.push('Scrim'); }
if (!findComp('Grabber')) { const c = comp('Grabber', 'HORIZONTAL', { primaryAxisAlignItems: 'CENTER', counterAxisAlignItems: 'CENTER' }); c.primaryAxisSizingMode = 'FIXED'; c.counterAxisSizingMode = 'FIXED'; c.resize(402, 44); sizeVar(c, 'height', 'touch'); const pill = figma.createFrame(); pill.name = 'Pill'; pill.resize(36, 5); radius(pill, 'full'); pill.fills = paint('outline'); sizeVar(pill, 'width', 'grabber-width'); c.appendChild(pill); c.description = 'Uchwyt arkusza dolnego. Tap przełącza połowę i pełną wysokość.'; await entry(b, 'Grabber', c.description, c); out.push('Grabber'); }
if (!findComp('Spinner')) { const c = figma.createComponent(); c.name = 'Spinner'; c.resize(18, 18); c.fills = []; const arc = figma.createEllipse(); arc.resize(18, 18); arc.fills = paint('on-surface'); arc.arcData = { startingAngle: 0, endingAngle: Math.PI * 1.5, innerRadius: 0.78 }; c.appendChild(arc); arc.constraints = { horizontal: 'SCALE', vertical: 'SCALE' }; c.description = 'Wskaźnik odświeżania po przeciągnięciu listy.'; await entry(b, 'Spinner', c.description, c); out.push('Spinner'); }
fitSection(s, b);
await shot(findComp('Button'), { name: 'ds-button', scale: 0.8 });
return out;
